---
name: Egg-Plugin-IxHash
version: 2.02
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: Tie::Hash::Indexed for Egg plugin.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Egg::Release: 2
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Tie::Hash::Indexed: 0.04
provides:
  Egg::Plugin::IxHash:
    file: lib/Egg/Plugin/IxHash.pm
    version: 2.02
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
